# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Coding in Stage 3"
email: "daniel.hickmott@uon.edu.au"
contact: "Daniel Hickmott"
baseurl: "/2018"

# Content Pages Paths
glossary_path: "/glossary"

# Day 1 Paths
maths_path: "/maths/"

# Day 2 Paths
steam_path: "/day2/"

# Build settings
markdown: kramdown
